## 维度变换
* View/reshape
* Squeeze/unsqueeze
* Transpose/t/permute
* Expand/repeat


In [8]:
import torch
a = torch.rand(4,1,28,28)
a

tensor([[[[0.7295, 0.0173, 0.8901,  ..., 0.0458, 0.8855, 0.4286],
          [0.4318, 0.5599, 0.8178,  ..., 0.6502, 0.1264, 0.4787],
          [0.3983, 0.2538, 0.6616,  ..., 0.8577, 0.7860, 0.4198],
          ...,
          [0.2878, 0.3797, 0.9540,  ..., 0.4108, 0.1313, 0.1910],
          [0.4590, 0.1471, 0.4318,  ..., 0.9068, 0.9482, 0.2631],
          [0.1414, 0.9322, 0.1992,  ..., 0.7625, 0.2551, 0.5539]]],


        [[[0.3247, 0.2941, 0.6151,  ..., 0.3611, 0.9294, 0.2660],
          [0.9192, 0.9472, 0.7803,  ..., 0.7166, 0.9875, 0.8350],
          [0.4200, 0.8611, 0.8524,  ..., 0.3000, 0.7025, 0.1265],
          ...,
          [0.4108, 0.8847, 0.4140,  ..., 0.9764, 0.3141, 0.9568],
          [0.7677, 0.9677, 0.3876,  ..., 0.3227, 0.4702, 0.9358],
          [0.1066, 0.0376, 0.1768,  ..., 0.5759, 0.8540, 0.9755]]],


        [[[0.3737, 0.5098, 0.8147,  ..., 0.9327, 0.2745, 0.1571],
          [0.1492, 0.9367, 0.8540,  ..., 0.8950, 0.7366, 0.3407],
          [0.2046, 0.9828, 0.8576,  ..

In [9]:
a.shape

torch.Size([4, 1, 28, 28])

In [10]:
a.view(4,28*28)

tensor([[0.7295, 0.0173, 0.8901,  ..., 0.7625, 0.2551, 0.5539],
        [0.3247, 0.2941, 0.6151,  ..., 0.5759, 0.8540, 0.9755],
        [0.3737, 0.5098, 0.8147,  ..., 0.9056, 0.5568, 0.4294],
        [0.7112, 0.2826, 0.6624,  ..., 0.6714, 0.1555, 0.7151]])

In [11]:
a.view(4,28*28).shape

torch.Size([4, 784])

In [12]:
a.view(4*28,28).shape

torch.Size([112, 28])

In [14]:
b = a.view(4,784)
b.view(4,28,28,1).shape

torch.Size([4, 28, 28, 1])

In [15]:
# 展开维度,增加额外的维度
a = torch.rand(4,1,28,28)
a.shape

torch.Size([4, 1, 28, 28])

In [16]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [17]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [18]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [19]:
a.unsqueeze(1).shape

torch.Size([4, 1, 1, 28, 28])

In [2]:
import torch
a = torch.tensor([1.2,3.4])

b = a.unsqueeze(-1)
print(b)
print(b.shape) #2,1

c = a.unsqueeze(0)
print(c)
print(c.shape) #1,2

"""
tensor([[1.2000],
        [3.4000]])
torch.Size([2, 1])
tensor([[1.2000, 3.4000]])
torch.Size([1, 2])
"""

tensor([[1.2000],
        [3.4000]])
torch.Size([2, 1])
tensor([[1.2000, 3.4000]])
torch.Size([1, 2])


'\ntensor([[1.2000],\n        [3.4000]])\ntorch.Size([2, 1])\ntensor([[1.2000, 3.4000]])\ntorch.Size([1, 2])\n'

In [3]:
# squeeze 维度挤压 维度删减
import torch

b = torch.rand(1,32,1,1)
b.shape

torch.Size([1, 32, 1, 1])

In [4]:
b.squeeze().shape

torch.Size([32])

In [8]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [7]:
b.squeeze(-1).shape

torch.Size([1, 32, 1])

In [6]:
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

In [5]:
b.squeeze(-4).shape


torch.Size([32, 1, 1])

## 拓展维度
* Expand : 改变维度方式，没有增加数据
* Repeat : 实实在在的增加了数据


In [9]:
a = torch.rand(4,32,14,14)

print(b.shape)
print(b.expand(4,32,14,14).shape)
print(b.expand(-1,32,-1,-1).shape)
print(b.expand(-1,32,-1,-4).shape)

torch.Size([1, 32, 1, 1])
torch.Size([4, 32, 14, 14])
torch.Size([1, 32, 1, 1])
torch.Size([1, 32, 1, -4])


In [10]:
# repeat 表示每一个维度所要拷贝的次数
print(b.shape)
print(b.repeat(4,32,1,1).shape)
print(b.repeat(4,1,1,1).shape)
print(b.repeat(4,1,32,32).shape)

torch.Size([1, 32, 1, 1])
torch.Size([4, 1024, 1, 1])
torch.Size([4, 32, 1, 1])
torch.Size([4, 32, 32, 32])


In [11]:
# 转置操作
a = torch.randn(3,4)
print(a)
print(a.shape)

b = a.t()
print(b)
print(b.shape)

tensor([[-0.4120, -0.0270, -2.3370,  1.5572],
        [ 1.6618,  0.1310,  0.7911, -0.5352],
        [-0.9059, -1.2209,  0.1778,  1.7793]])
torch.Size([3, 4])
tensor([[-0.4120,  1.6618, -0.9059],
        [-0.0270,  0.1310, -1.2209],
        [-2.3370,  0.7911,  0.1778],
        [ 1.5572, -0.5352,  1.7793]])
torch.Size([4, 3])


In [17]:
# 维度之间转置 transpose
a = torch.rand(4,3,32,32)

# a1 = a.transpose(1,3).view(4,3*32*32).view(4,3,32,32)

a1 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32)

a2 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32).transpose(1,3)

print(a1.shape,a2.shape)

# print(torch.all(torch.eq(a,a1)))
# print(torch.all(torch.eq(a,a2)))

torch.Size([4, 3, 32, 32]) torch.Size([4, 32, 32, 3])


In [3]:
# 更加方便的转置维度
import torch
a = torch.rand(4,3,28,28)

print(a.transpose(1,3).transpose(1,2).shape)

print(a.permute(0,2,3,1).shape)

torch.Size([4, 28, 28, 3])
torch.Size([4, 28, 28, 3])
